#!/bin/sh

export PATH=/home/spetit/dev/IdeaProjects/ddd-hexagonal-template/frontend/build/npm/npm-v6.13.4/bin:/home/spetit/dev/IdeaProjects/ddd-hexagonal-template/frontend/build/node/node-v12.16.1-linux-x64/bin:$PATH
npm "$@"